[20200602]
date = 2020-06-02
name = "Congressional & Presidential Primary"
original_date = 2020-06-02

[20201103]
date = 2020-11-03
name = "General"
original_date = 2020-11-03

[20201103.registration]
in_person_by = 2020-10-31 # Same day in person Saturday before at County Office
online_by = 2020-10-06 # 28 Days prior to election
postmarked_by = 2020-10-06 
received_by = 2020-10-07 # if postmarked_by 28 days berfore
sources = ["https://www.sos.state.nm.us/voting-and-elections/voting-faqs/voter-registration/"] 

[20201103.absentee.application]
online_by = 2020-10-20T17:00:00
received_by = 2020-10-20T17:00:00
sources = ["https://www.sos.state.nm.us/voting-and-elections/voting-faqs/absentee-voting-by-mail/"]

[20201103.absentee]
received_by = 2020-11-03T19:00:00
sources = ["https://www.sos.state.nm.us/voting-and-elections/voting-faqs/absentee-voting-by-mail/"]

[20201103.poll.early]
in_person_by = 2020-10-31 
in_person_start = 2020-10-06 # 28 Days prior to election at County Office
sources = ["https://www.sos.state.nm.us/voting-and-elections/voting-faqs/early-voting-in-person/"] 

[20201103.poll]
in_person_by = 2020-11-03T19:00:00 # Hours are according to Ballotpedia
in_person_start = 2020-11-03T07:00:00 
sources = ["https://ballotpedia.org/Voting_in_New_Mexico"]
