[20200602]
date = 2020-06-02
name = "Congressional Primary"
original_date = 2020-06-02

[20201103]
date = 2020-11-03
name = "General"
original_date = 2020-11-03

[20201103.registration]
in_person_by = 2020-11-03
online_by = 2020-10-24
received_by = 2020-10-24
sources = [
  "https://sos.iowa.gov/elections/electioninfo/3yrelectioncal.html",
  "https://sos.iowa.gov/elections/voterinformation/voterregistration.html",
  "https://sos.iowa.gov/elections/voterinformation/edr.html",
]

[20201103.absentee.application]
received_by = 2020-10-24T17:00:00 # Saturday 10 days before General
sources = [
  "https://sos.iowa.gov/elections/electioninfo/absenteeinfo.html",
  "https://sos.iowa.gov/elections/electioninfo/absenteemail.html",
] 

[20201103.absentee]
in_person_by = 2020-11-03 # At County Auditor, not polling places
postmarked_by = 2020-11-02 # Monday before election day
received_by = 2020-11-09T12:00:00 # By Noon Monday after election day

# [20201103.poll.early] Not a thing

[20201103.poll]
in_person_by = 2020-11-03T21:00:00
in_person_start = 2020-11-03T07:00:00
sources = ["https://sos.iowa.gov/elections/voterreg/pollingplace/search.aspx"]
