[20200609]
date = 2020-06-09
name = "Congressional Primary"
original_date = 2020-06-09

[20201103]
date = 2020-11-03
name = "General"
original_date = 2020-11-03

[20201103.registration]
in_person_by = 2020-10-06
online_by = 2020-10-29
postmarked_by = 2020-10-06
sources = ["https://www.nvsos.gov/sos/home/showdocument?id=8206"]

[20201103.absentee.application]
received_by = 2020-10-20
sources = ["https://www.nvsos.gov/sos/home/showdocument?id=8206"]

[20201103.absentee]
in_person_by = 2020-11-03T19:00:00
postmarked_by = 2020-11-03
received_by = 2020-11-10
sources = [
  "https://www.nvsos.gov/sos/home/showdocument?id=8206",
  "https://www.nvsos.gov/sos/elections/voters/absentee-voting",
]

[20201103.poll.early]
in_person_by = 2020-10-30
in_person_start = 2020-10-17
sources = ["https://www.nvsos.gov/sos/home/showdocument?id=8206"]

[20201103.poll]
in_person_by = 2020-11-03T19:00:00
in_person_start = 2020-11-03T07:00:00
postmarked_by = 2020-11-03
sources = ["https://www.nvsos.gov/sos/elections/election-information/2020-election/2020-general-election"]
