[20200303]
date = 2020-03-03
name = "Presidential Primary (Democrats)"
original_date = 2020-03-03

[20200623]
date = 2020-06-23
name = "Congressional Primary"
original_date = 2020-06-23

[20200623.poll]
in_person_by = 2020-06-23

[20200623.absentee]
in_person_by = 2020-06-23
received_by = 2020-06-23

[20201103]
date = 2020-11-03
name = "General"
original_date = 2020-11-03

[20201103.registration]
in_person_by = 2020-10-12T17:00:00
online_by = 2020-10-12T17:00:00
received_by = 2020-10-12T17:00:00
sources = ["https://www.elections.virginia.gov/registration/", "https://www.elections.virginia.gov/registration/how-to-register/"]

[20201103.absentee.application]
received_by = 2020-10-23T17:00:00
in_person_by = 2020-10-31T17:00:00
sources = ["https://www.elections.virginia.gov/casting-a-ballot/absentee-voting/", "https://www.elections.virginia.gov/casting-a-ballot/calendars-schedules/upcoming-elections.html"]

[20201103.absentee]
postmarked_by = 2020-11-03T19:00:00
received_by = 2020-11-06T12:00:00
sources = ["https://www.elections.virginia.gov/registration/election-voter-faq/"]

[20201103.poll.early]
in_person_start = 2020-09-18
in_person_by = 2020-10-31
sources = ["https://www.elections.virginia.gov/casting-a-ballot/absentee-voting/"]

[20201103.poll]
in_person_start = 2020-11-03T06:00:00
in_person_by = 2020-11-03T19:00:00