[20200623]
date = 2020-06-23
name = "Congressional Primary Run-Off"
original_date = 2020-06-23

[20200623.registration]
in_person_by = 2020-05-26
postmarked_by = 2020-05-26

[20200623.absentee]
# postmarked_by = 2020-06-23
received_by = 2020-06-22T17:00:00
sources = ["https://www.sos.ms.gov/content/documents/elections/2020%20Website%20Calendar.pdf"]

[20200623.poll]
in_person_by = 2020-06-23

[20201103]
date = 2020-11-03
name = "General"
original_date = 2020-11-03

[20201103.registration]
postmarked_by = 2020-10-05 # 30 days prior
in_person_by = 2020-10-05 # 30 days prior
sources = ["https://www.sos.ms.gov/content/documents/elections/2020%20Website%20Calendar.pdf"]

[20201103.absentee.application]
received_by = 2020-10-20 # Padded 14 Days
sources = ["https://www.sos.ms.gov/content/documents/Elections/MSCODE_Elections.pdf"] 
# See 23-15-687.. I don't see a cut-off, only a 24 turn around to mail ballot

[20201103.absentee]
in_person_by = 2020-10-31T12:00:00
received_by = 2020-11-02T17:00:00
sources = ["https://www.sos.ms.gov/content/documents/elections/2020%20Website%20Calendar.pdf"]

[20201103.poll]
in_person_start = 2020-11-03T07:00:00
in_person_by = 2020-11-03T19:00:00
sources = ["https://www.sos.ms.gov/content/documents/elections/2020%20Website%20Calendar.pdf"]
