name = "North Dakota"
fips_code = 38
postal_code = "ND"
homepage = "http://vote.nd.gov/"
registration_info = "https://vip.sos.nd.gov/pdfs/Portals/votereg.pdf" # North Dakota requires no voter registration
absentee_info = "https://vip.sos.nd.gov/absentee/Default.aspx"
military_overseas_info = "https://vip.sos.nd.gov/PortalListDetails.aspx?ptlhPKID=51&ptlPKID=7#content-start"
demonym = "North Dakotan"
elections_twitter = [""]
governor_twitter = ["DougBurgum"]
sos_twitter = [""]