[20200428]
date = 2020-04-28
name = "Congressional & Presidential Primary"
original_date = 2020-04-28

[20201103]
date = 2020-11-03
name = "General"
original_date = 2020-11-03

[20201103.registration]
online_by = 2020-10-05
received_by = 2020-10-05
sources = ["https://olvr.ohiosos.gov/"]

[20201103.absentee.application]
received_by = 2020-10-31T12:00:00
sources = [
  "https://www.sos.state.oh.us/elections/voters/absentee-voting/#byMail",
  "https://www.sos.state.oh.us/elections/voters/current-voting-schedule/",
]

[20201103.absentee]
in_person_by = 2020-11-03T19:30:00
postmarked_by = 2020-11-02
received_by = 2020-11-13
sources = [
  "https://www.sos.state.oh.us/elections/voters/absentee-voting/#byMail",
  "https://www.sos.state.oh.us/elections/voters/current-voting-schedule/",
]

[20201103.poll.early]
in_person_by = 2020-11-02
in_person_start = 2020-10-06
sources = [
  "https://www.sos.state.oh.us/elections/voters/absentee-voting/#inPerson",
  "https://www.sos.state.oh.us/elections/voters/current-voting-schedule/",
]

[20201103.poll]
in_person_by = 2020-11-03T19:30:00
in_person_start = 2020-11-03T06:30:00
sources = ["https://www.sos.state.oh.us/elections/voters/current-voting-schedule/"]
